# Generated by Django 4.0.4 on 2022-05-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_authors_book_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookauthor',
            name='twitter_username',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
