# Generated by Django 4.0.4 on 2022-05-17 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_bookrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrecord',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddConstraint(
            model_name='bookrecord',
            constraint=models.CheckConstraint(check=models.Q(('rating__range', (1, 5))), name='books_bookrecord_rating_range'),
        ),
    ]
